# Generated by Django 4.0.5 on 2022-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.URLField(default='https://forum-db.s3.ap-south-1.amazonaws.com/media/default.jpg', verbose_name='Profile Picture'),
        ),
    ]
