# Generated by Django 3.2.9 on 2021-11-09 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.CreateModel(
            name='ChannelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_name', models.CharField(blank=True, max_length=20)),
                ('Channel_admin_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin_1', to=settings.AUTH_USER_MODEL)),
                ('Channel_admin_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
