# Generated by Django 4.0 on 2022-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member',
            field=models.ManyToManyField(to='Forum_App.Channel'),
        ),
    ]
