# Generated by Django 4.0 on 2022-01-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
        ('AuthenticationApp', '0002_userprofile_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='member',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_of',
            field=models.ManyToManyField(to='Forum_App.Channel', verbose_name='Member of'),
        ),
    ]
