# Generated by Django 4.0.3 on 2022-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.URLField(default='default/bg.jpeg', verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ISE', 'Information Science and Engineering'), ('ECE', 'Electronics and Communications Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil'), ('MECH', 'Mechanical')], max_length=5, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.URLField(default='default/user_image.jpeg', verbose_name='Profile Picture'),
        ),
    ]
