# Generated by Django 4.0 on 2022-01-02 10:34

import AuthenticationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_alter_userprofile_member_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('', ''), ('CSE', 'CSE'), ('ISE', 'ISE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH')], max_length=5, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Miss.'), ('Mrs.', 'Mrs.')], max_length=4, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.FileField(blank=True, upload_to=AuthenticationApp.models.UserProfile.path_and_rename, verbose_name='User Image'),
        ),
    ]
