# Generated by Django 4.0.3 on 2022-04-19 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Channel Name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this channel should be treated as active. Unselect this instead of deleting channels.', verbose_name='Is active')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Channel_Admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Channel Member')),
                ('moderator', models.ManyToManyField(related_name='Moderator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'db_table': 'channel',
                'unique_together': {('name', 'admin')},
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField(verbose_name='File Path')),
                ('file_type', models.CharField(max_length=10, verbose_name='File Type ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Post text')),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Designates whether this post should be treated as hidden.Unselect this instead of deleting post.', verbose_name='Is Hidden')),
                ('posted_in', models.ManyToManyField(related_name='Post_Channel', to='Forum_App.channel')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Designates whether this comment should be treated as visible. Unselect this instead of deleting comment.', verbose_name='Is Hidden')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commented_Post', to='Forum_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Commented', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'post_comment',
            },
        ),
        migrations.CreateModel(
            name='UserPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Media', to='Forum_App.media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='Forum_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post_User_Media',
                'verbose_name_plural': 'post_user_media',
                'db_table': 'post_user_media',
                'unique_together': {('user', 'post', 'media')},
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liked_Post', to='Forum_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'post_likes',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
