# Generated by Django 4.0 on 2022-03-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='member_of',
            new_name='members',
        ),
    ]
