# Generated by Django 4.0 on 2021-12-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100, verbose_name='Comment')),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=True, help_text='Designates whether this comment should be treated as visible. Unselect this instead of deleting comment.', verbose_name='Is Hidden')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Designates whether this post should be treated as hidden. Unselect this instead of deleting post.', verbose_name='Is Hidden'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-22 19:20:49,194734'),
        ),
        migrations.DeleteModel(
            name='Post_Comments',
        ),
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commented_Post', to='Forum_App.post'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Commented', to='AuthenticationApp.userprofile'),
        ),
    ]
