# Generated by Django 3.2.9 on 2021-11-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post_Likes',
            new_name='Post_Like',
        ),
        migrations.AddField(
            model_name='post_detail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is_Active'),
        ),
        migrations.AlterField(
            model_name='post_detail',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Post-Text'),
        ),
        migrations.AlterField(
            model_name='post_detail',
            name='image_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of images attached to post'),
        ),
        migrations.AlterField(
            model_name='post_detail',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Post-Time'),
        ),
        migrations.DeleteModel(
            name='Post_Comments',
        ),
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_Comment', to='Forum_App.post_detail'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
