# Generated by Django 3.2.9 on 2021-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Post-Text'),
        ),
    ]
