# Generated by Django 4.0 on 2022-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(default='image', max_length=10, verbose_name='File Type '),
        ),
    ]
