# Generated by Django 4.0 on 2022-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0002_alter_media_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(max_length=100, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(max_length=10, verbose_name='File Type '),
        ),
    ]
