# Generated by Django 3.2.9 on 2021-11-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0002_alter_postdetail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimagestore',
            name='post',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='Post_Id', to='Forum_App.postdetail'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
