# Generated by Django 4.0.3 on 2022-04-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0002_post_edited_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
