# Generated by Django 4.0 on 2021-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('Forum_App', '0002_post_comment_alter_post_is_hidden_alter_post_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Likes',
            new_name='Post_Like',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-22 19:21:24,315252'),
        ),
    ]
