# Generated by Django 4.0.3 on 2022-04-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum_App', '0003_postlikes_rename_post_comment_postcomments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostmedia',
            options={'verbose_name': 'post_User_Media', 'verbose_name_plural': 'post_user_media'},
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
