# Generated by Django 4.0 on 2022-01-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_alter_userprofile_department_and_more'),
        ('Forum_App', '0003_alter_user_post_media_media'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_post_media',
            unique_together={('user', 'post', 'media')},
        ),
    ]
