# Generated by Django 4.0 on 2022-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0003_alter_media_file_alter_media_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.URLField(verbose_name='File Path'),
        ),
    ]
