# Generated by Django 4.0 on 2021-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('Forum_App', '0003_rename_post_likes_post_like_alter_post_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Comment',
            new_name='PostComment',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-22 19:22:44,251928'),
        ),
    ]
