# Generated by Django 4.0 on 2021-12-24 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum_App', '0004_rename_post_comment_postcomment_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='moderator',
            field=models.ManyToManyField(related_name='Moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-24 10:20:38,921071'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Designates whether this comment should be treated as visible. Unselect this instead of deleting comment.', verbose_name='Is Hidden'),
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
