# Generated by Django 4.0.3 on 2022-04-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0004_alter_userpostmedia_options_alter_postlikes_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcomments',
            unique_together=set(),
        ),
    ]
