# Generated by Django 4.0 on 2022-01-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0004_alter_user_post_media_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_post_media',
            unique_together=set(),
        ),
    ]
