# Generated by Django 4.0 on 2021-12-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('Forum_App', '0006_alter_post_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Post_Comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-24 18:01:28,214973'),
        ),
        migrations.CreateModel(
            name='User_Post_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Media', to='Forum_App.media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='Forum_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='AuthenticationApp.userprofile')),
            ],
        ),
    ]
