# Generated by Django 4.0 on 2021-12-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('Forum_App', '0007_rename_postcomment_post_comment_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2021-12-24 18:09:28,312755'),
        ),
        migrations.AlterUniqueTogether(
            name='post_like',
            unique_together={('user', 'post')},
        ),
    ]
